export default {
    LOGIN: 'LOGIN',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    GET_USERS: 'GET_USERS',
    GET_FOODS: 'GET_FOODS',
    CREATE_FOOD: 'CREATE_FOOD',
    GET_REPORTS: 'GET_REPORTS',
    CREATE_REPORT: 'CREATE_REPORT',
    UPDATE_REPORT: 'UPDATE_REPORT',
}